baseURL = "https://cran-checks-docs.netlify.app"
languageCode = "en-us"
title = "CRAN Checks API Docs"
disableKinds = ["taxonomyTerm"]
enableEmoji = true
pygmentsUseClasses=true

theme = "docuapi"
themesdir = "themes"

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[languages.en]
languageName = "English"
weight = 2
title = "CRAN checks API"
# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi),",
" Hugo and R",
"[Website source](https://maelle/cranchecksdocs)"
]

[params]
search = true
custom_css = ["css/custom.css", "css/code.css"]
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "r"
name = "R" 
[[params.language_tabs]]
key = "shell"
name = "Shell"
otherlangs = ["json", "xml"]
[[params.language_tabs]]
key = "yaml"
name = "Headers"

ignoreFiles = ["\\.Rmd$", "\\.html$", "\\_cache"]