on:
  push:
    branches: master
  schedule:
    - cron:  '30 12 * * 1'

name: render

jobs:
  render:
    runs-on: macOS-latest
    if: "github.event_name == 'schedule' || contains(github.event.head_commit.message, '[docs]')"
     steps:
      - uses: actions/checkout@v2
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Render Rmd
        run: Rscript -e 'source("make.R")'
      - name: Commit results
        run: |
          git commit * -m 'Re-build docs' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
